import { useSession } from "next-auth/react"
import Head from "next/head"
import Layout from "../components/layout"
import MePage from "./me"

export default function IndexPage() {
  const { data } = useSession()
  return (
    <Layout>
      <Head>
        <title>Dev Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet"></link>
      </Head>
      <h1>Dev Portal</h1>
      <p>
        This is an example site to demonstrate how to use{" "}
        <a href="https://next-auth.js.org">NextAuth.js</a> for authentication.
      </p>
      {data && <MePage />}
    </Layout>

  )
}
